spring.application.name=practice

spring.datasource.driver-class-name = oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=system
spring.datasource.password=11111111

mybatis.mapper-locations = classpath:mappers/*.xml

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# 템플릿 캐시. 매 요청마다 읽게
spring.thymeleaf.cache=true
# 정적 파일 캐시
spring.web.resources.cache.cachecontrol.max-age=0
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# 이미지 경로 표시
spring.web.resources.static-locations=classpath:, classpath:/static/image/, classpath:/static/

#logging.level.root=DEBUG